// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int high = 0;
		int lowequal = 0;
		int rcount = 0;
		double ratio = 0;
		while (rcount<N){
			double m = Math.random();
			if (m>0.5){
				high++;
			}
			else{
				lowequal++;
			}
			rcount++;
		}
		if(high >= lowequal){
			ratio = (double)lowequal/(double)high;
		}
		else {
			ratio = (double)((double)high/(double)lowequal);
		}
		System.out.println("> 0.5:  " + high + " times");
		System.out.println("<= 0.5: " + lowequal + " times");
		if((high!=0) && (lowequal!=0)){
			System.out.println("Ratio:  " + ratio);	
		}
	}
}
